### ISSUE TITLE
GitHub scanning permissions - do not require read of GitHub repo secrets.

### ISSUE THREAD

**Issue by scottford-io** [mondoohq/docs#456]
#### Summarize the content issue

When integrating GitHub using the new GitHub App, our docs say the user should configure Read-Only to all org and repo data. Verily reported that the Repository Secrets configuration only provides "Read/Write" which raised a security concern. 

Does Mondoo really use the Repository Secrets API and do we need "Read/Write" access?

#### URL(s)

https://mondoo.com/docs/cnspec/saas/gh-app/

#### What the docs say

_Under Permissions, assign read-only permission to all repository and organization data._

#### What the docs SHOULD say

Provide the correct info here (if you know it).

#### Screenshots

![Image](https://github.com/user-attachments/assets/d385417a-51bf-462b-85e7-0380ded103b4)

#### References

If applicable, provide links to relevant sources of info.

#### Notes

Add any other info you want to provide.

**Comment by misterpantz** [comment]
@chris-rock just said to give read-only access to everything. I imagine that was just a rushed answer, considering the pressure to get the docs completed for Verily that day. I'm sure not all of them are required, and it's in my backlog to test this when I can, since this is the only answer I can get from eng.

**Comment by alayshia** [comment]
> Verily reported that the Repository Secrets configuration only provides "Read/Write" which raised a security concern.

Under both Repository and Organization Permissions, "Secrets" has "No Access," "Read-Only," and "Read and Write" Options. In my configuration, I provided "No access" for these options. I will investigate the code to see if we use the secrets API. @afiune

**Comment by misterpantz** [comment]
That would be fantastic, @alayshia!

**Comment by alayshia** [comment]
I glanced at our core policy and the github resource provider, and there was no indication that we were hitting any secrets API. We can update the docs to reflect that it is not required.

**Comment by misterpantz** [comment]
So you want to say "everything but..."? I would really rather say what IS required.

**Comment by misterpantz** [comment]
I'm sorry my question wasn't clear. As I said a few comments ago, I'm sure there are many perms that aren't actually necessary. And I would like to tell the customers only what is necessary. I spoke with @afiune and he's on it. Thanks, @afiune!

**Comment by afiune** [comment]
Most of the things we collect/discover are in this file https://github.com/mondoohq/cnquery/blob/main/providers/github/resources/github.lr

If we search for `github.` you will see organizations, repositories, users, etc. 

I don't see things like GH actions, checks or code spaces, though, asking for read-only is the right thing to do since, if we don't and we add discovery for those assets, customers will have to reconfigure their integrations which we probably don't want.

I say let's stay as we are, as much read-only access as possible, **without** any write at all.

**Comment by misterpantz** [comment]
Thanks, @afiune.

So basically if a perm has read-only access as an option, we want users to give Mondoo read-only access. And if read-only access is NOT an option for a perm, users should not give Mondoo any access. Accurate?

**Comment by afiune** [comment]
Yes! That's accurate.

**Comment by misterpantz** [comment]
Thanks very much. I'll doc it!

**Comment by misterpantz** [comment]
Summary of solution: Well we still don't know for sure exactly what is required. But we eased customer pain.concern quite a bit by making it clear that if there's no read-only option, you can leave it set to No Access.
